### PR TITLE
Addition of verbose patch for error messages to 0.10.0

### PR DESCRIPTION
**Pull request by FrankD412**

### CODE REVIEW

**Comment by bhatiaharsh** [comment]
Frank, can you change the request to merge into "bhatia-splash" ?

**Comment by FrankD412** [comment]
Oh, good catch. done.

**Comment by bhatiaharsh** [comment]
also, i am not sure how spack would apply the patch. we would also somehow need to add this to the package file.

**Comment by FrankD412** [comment]
Oh, I thought that file was added. I might have readded the same file accidentally. Hold on, I have a change for it.

**Pull request merged**
